FROM node:14 AS builder

WORKDIR /app

COPY package.json ./

COPY prisma ./prisma/


RUN npm install


#COPY .env .



#RUN npx prisma generate

#RUN npx prisma db push

#RUN npx prisma db seed
COPY . .



EXPOSE 3000


CMD ["npm", "run", "dev"] 



#prismma see